// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID         []byte
	CreatedOn  pgtype.Date
	ModifiedOn pgtype.Date
	Vat        pgtype.Text
	Name       pgtype.Text
	Address    pgtype.Text
	Phone      pgtype.Int8
}

type Inventory struct {
	MaterialID       []byte
	Quantity         pgtype.Int4
	DateLastModified pgtype.Date
}

type Material struct {
	ID          []byte
	Picture     pgtype.Text
	Description pgtype.Text
	Name        pgtype.Text
	SupplierID  []byte
	UnitID      []byte
}

type Recipe struct {
	ID          []byte
	ProductName pgtype.Text
	Description pgtype.Text
}

type RecipeMaterial struct {
	RecipeID   []byte
	MaterialID []byte
	UnitID     []byte
}

type Supplier struct {
	ID    []byte
	Name  pgtype.Text
	Email pgtype.Text
	Phone pgtype.Int4
}

type TransactionHistory struct {
	ID           []byte
	Date         pgtype.Date
	Details      pgtype.Text
	Type         pgtype.Text
	Price        pgtype.Numeric
	DocumentPath pgtype.Text
	Destination  pgtype.Text
	MaterialID   []byte
}

type Unit struct {
	ID         []byte
	UnitString pgtype.Text
}

type User struct {
	Email        string
	CreatedOn    pgtype.Date
	ModifiedOn   pgtype.Date
	PasswordHash []byte
	Username     pgtype.Text
	CompanyID    []byte
}
